services:
  mysql_db:
    image: mysql:8.0
    ports: 
      - "3307:3307"
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  phpMyAdmin:
    image: phpmyadmin:5.0
    ports:
      - "8081:80"
    environment:
      PMA_HOSTS:  mysql_db
      MYSQL_ROOT_PASSWORD: root